# Generated by Django 4.2.13 on 2024-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_danhgia_nguoidanhgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='nguoidanhgia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
